
spring:
  datasource:
    url:  jdbc:mysql://${MYSQL_CONTAINER_NAME:localhost}:3306/${MYSQL_DATABASE:hold_release_area}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driverClassName: com.mysql.cj.jdbc.Driver

server:
  port: 8083
