spring:
  datasource:
    url:  jdbc:mysql://${MYSQL_CONTAINER_NAME:localhost}:3306/${MYSQL_DATABASE:hold_release_area}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driverClassName: com.mysql.cj.jdbc.Driver
    
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer

  activemq:
    broker-url: ${ACTIVE_MQ_HOST:tcp://localhost:61616}
    in-memory: false
  jpa:
    show-sql: true
    hibernate:
      dialext: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update
      
transaction:
  queue: transaction.message.queue
  
server.port: 8081
  
---
spring:
  profiles: test

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  activemq:
    broker-url: vm://localhost?broker.persistent=false
    in-memory: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
